import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner";
import { ClipboardList, Package } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PortalShell, PortalHeading } from "@/components/portal-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { STATUS_LABEL, STATUS_ORDER, type ShipmentStatus } from "@/lib/nexora";

export const Route = createFileRoute("/_authenticated/admin/tracking")({ component: TrackingAdmin });
const nav=[{to:"/admin",label:"Overview",icon:ClipboardList,exact:true},{to:"/admin/shipments",label:"Shipments",icon:Package},{to:"/admin/customers",label:"Customers",icon:Package},{to:"/admin/tracking",label:"Tracking",icon:ClipboardList},{to:"/dashboard",label:"Customer portal",icon:Package}];
function TrackingAdmin(){const [shipmentId,setShipmentId]=useState("");const [form,setForm]=useState({status:"in_transit" as ShipmentStatus,location:"",note:"",occurred_at:new Date().toISOString().slice(0,16)});const q=useQuery({queryKey:["tracking-admin-shipments"],queryFn:async()=>{const {data,error}=await supabase.from("shipments").select("id,tracking_number,origin,destination,status").order("updated_at",{ascending:false});if(error)throw error;const {data:u}=await supabase.auth.getUser();return {shipments:data??[],email:u.user?.email}}});async function submit(e:React.FormEvent){e.preventDefault();if(!shipmentId)return toast.error("Select a shipment");const {error}=await supabase.from("shipment_events").insert({shipment_id:shipmentId,status:form.status,location:form.location||null,note:form.note||null,occurred_at:new Date(form.occurred_at).toISOString()});if(error)toast.error(error.message);else{toast.success("Tracking update published");setForm(x=>({...x,note:"",location:""}))}}return <PortalShell kind="Admin console" email={q.data?.email} nav={nav}><PortalHeading title="Tracking" subtitle="Publish a status update and it immediately appears on the customer timeline."/><form onSubmit={submit} className="panel mt-6 max-w-2xl p-6 space-y-5"><div><Label className="eyebrow">Shipment</Label><Select value={shipmentId} onValueChange={setShipmentId}><SelectTrigger className="mt-2 rounded-none"><SelectValue placeholder="Select shipment"/></SelectTrigger><SelectContent>{q.data?.shipments.map(s=><SelectItem key={s.id} value={s.id}>{s.tracking_number} — {s.origin} → {s.destination}</SelectItem>)}</SelectContent></Select></div><div><Label className="eyebrow">Status</Label><Select value={form.status} onValueChange={v=>setForm(x=>({...x,status:v as ShipmentStatus}))}><SelectTrigger className="mt-2 rounded-none"><SelectValue/></SelectTrigger><SelectContent>{STATUS_ORDER.concat(["exception"]).map(v=><SelectItem key={v} value={v}>{STATUS_LABEL[v]}</SelectItem>)}</SelectContent></Select></div><div><Label className="eyebrow">Location</Label><Input value={form.location} onChange={e=>setForm(x=>({...x,location:e.target.value}))} className="mt-2 rounded-none"/></div><div><Label className="eyebrow">Update note</Label><Textarea value={form.note} onChange={e=>setForm(x=>({...x,note:e.target.value}))} className="mt-2 rounded-none"/></div><div><Label className="eyebrow">Event time</Label><Input type="datetime-local" value={form.occurred_at} onChange={e=>setForm(x=>({...x,occurred_at:e.target.value}))} className="mt-2 rounded-none"/></div><Button type="submit" className="rounded-none">Publish update</Button></form></PortalShell>}
