/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardShipmentsRouteImport } from './routes/_authenticated/dashboard.shipments'
import { Route as AuthenticatedDashboardShipmentDetailRouteImport } from './routes/_authenticated/dashboard.shipments.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminShipmentsRouteImport } from './routes/_authenticated/admin.shipments'
import { Route as AuthenticatedAdminShipmentDetailRouteImport } from './routes/_authenticated/admin.shipments.$id'
import { Route as AuthenticatedAdminNewShipmentRouteImport } from './routes/_authenticated/admin.shipments.new'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated/admin.tracking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardShipmentsRoute = AuthenticatedDashboardShipmentsRouteImport.update({ id: '/dashboard/shipments', path: '/shipments', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDashboardShipmentDetailRoute = AuthenticatedDashboardShipmentDetailRouteImport.update({ id: '/dashboard/shipments/$id', path: '/shipments/$id', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAdminShipmentsRoute = AuthenticatedAdminShipmentsRouteImport.update({ id: '/admin/shipments', path: '/shipments', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAdminShipmentDetailRoute = AuthenticatedAdminShipmentDetailRouteImport.update({ id: '/admin/shipments/$id', path: '/shipments/$id', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAdminNewShipmentRoute = AuthenticatedAdminNewShipmentRouteImport.update({ id: '/admin/shipments/new', path: '/shipments/new', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAdminCustomersRoute = AuthenticatedAdminCustomersRouteImport.update({ id: '/admin/customers', path: '/customers', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAdminTrackingRoute = AuthenticatedAdminTrackingRouteImport.update({ id: '/admin/tracking', path: '/tracking', getParentRoute: () => AuthenticatedRouteRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard/shipments': typeof AuthenticatedDashboardShipmentsRoute
  '/dashboard/shipments/$id': typeof AuthenticatedDashboardShipmentDetailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/shipments': typeof AuthenticatedAdminShipmentsRoute
  '/admin/shipments/$id': typeof AuthenticatedAdminShipmentDetailRoute
  '/admin/shipments/new': typeof AuthenticatedAdminNewShipmentRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard/shipments': typeof AuthenticatedDashboardShipmentsRoute
  '/dashboard/shipments/$id': typeof AuthenticatedDashboardShipmentDetailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/shipments': typeof AuthenticatedAdminShipmentsRoute
  '/admin/shipments/$id': typeof AuthenticatedAdminShipmentDetailRoute
  '/admin/shipments/new': typeof AuthenticatedAdminNewShipmentRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard/shipments': typeof AuthenticatedDashboardShipmentsRoute
  '/_authenticated/dashboard/shipments/$id': typeof AuthenticatedDashboardShipmentDetailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin/shipments': typeof AuthenticatedAdminShipmentsRoute
  '/_authenticated/admin/shipments/$id': typeof AuthenticatedAdminShipmentDetailRoute
  '/_authenticated/admin/shipments/new': typeof AuthenticatedAdminNewShipmentRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/tracking': typeof AuthenticatedAdminTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/quote' | '/services' | '/track' | '/dashboard' | '/dashboard/shipments' | '/dashboard/shipments/$id' | '/admin' | '/admin/shipments' | '/admin/shipments/$id' | '/admin/shipments/new' | '/admin/customers' | '/admin/tracking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/quote' | '/services' | '/track' | '/dashboard' | '/dashboard/shipments' | '/dashboard/shipments/$id' | '/admin' | '/admin/shipments' | '/admin/shipments/$id' | '/admin/shipments/new' | '/admin/customers' | '/admin/tracking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/quote'
    | '/services'
    | '/track'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/shipments'
    | '/_authenticated/dashboard/shipments/$id'
    | '/_authenticated/admin'
    | '/_authenticated/admin/shipments'
    | '/_authenticated/admin/shipments/$id'
    | '/_authenticated/admin/shipments/new'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/quote': { id: '/quote'; path: '/quote'; fullPath: '/quote'; preLoaderRoute: typeof QuoteRouteImport; parentRoute: typeof rootRouteImport }
    '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
    '/track': { id: '/track'; path: '/track'; fullPath: '/track'; preLoaderRoute: typeof TrackRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dashboard/shipments': { id: '/_authenticated/dashboard/shipments'; path: '/dashboard/shipments'; fullPath: '/dashboard/shipments'; preLoaderRoute: typeof AuthenticatedDashboardShipmentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dashboard/shipments/$id': { id: '/_authenticated/dashboard/shipments/$id'; path: '/dashboard/shipments/$id'; fullPath: '/dashboard/shipments/$id'; preLoaderRoute: typeof AuthenticatedDashboardShipmentDetailRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin': { id: '/_authenticated/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AuthenticatedAdminRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/shipments': { id: '/_authenticated/admin/shipments'; path: '/admin/shipments'; fullPath: '/admin/shipments'; preLoaderRoute: typeof AuthenticatedAdminShipmentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/shipments/$id': { id: '/_authenticated/admin/shipments/$id'; path: '/admin/shipments/$id'; fullPath: '/admin/shipments/$id'; preLoaderRoute: typeof AuthenticatedAdminShipmentDetailRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/shipments/new': { id: '/_authenticated/admin/shipments/new'; path: '/admin/shipments/new'; fullPath: '/admin/shipments/new'; preLoaderRoute: typeof AuthenticatedAdminNewShipmentRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/customers': { id: '/_authenticated/admin/customers'; path: '/admin/customers'; fullPath: '/admin/customers'; preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/tracking': { id: '/_authenticated/admin/tracking'; path: '/admin/tracking'; fullPath: '/admin/tracking'; preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
  }
}

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
